# Generated by Django 5.1.4 on 2025-02-24 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_like_options_alter_like_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog_post',
            new_name='post',
        ),
    ]
