# Generated by Django 5.1.4 on 2025-02-25 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_post_comment_blog_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='blog_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost'),
        ),
    ]
