# Generated by Django 5.1.4 on 2025-02-25 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_like_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='blog_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost'),
            preserve_default=False,
        ),
    ]
