# Generated by Django 5.1.4 on 2025-02-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_rename_author_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='blog_post',
            new_name='post',
        ),
    ]
